### ISSUE TITLE
Column header after update

### ISSUE THREAD

**Issue by mado-longasa** [RoXuS/paper-datatable-api#31] opened 2017-03-15 06:44 UTC
Frozen header scrolled back after editing column content but the table body stays on its last position.
Is it possible to align both header and column after editing?

**Comment by RoXuS** [comment] 2017-03-15 10:49
Hello @mado-longasa,

Can you try to call `_resizeHeader` after editing ?

**Comment by mado-longasa** [comment] 2017-03-16 00:08
Hello @RoXuS thanks for the quick reply 

I tried to call _resizeHeader after update but still encountering  the same issue. 

here's what I've done

this.$.table.data = JSON.parse(JSON.stringify(this.data));
this.$.table._resizeHeader();

**Comment by RoXuS** [comment] 2017-03-16 09:56
Can you provide me a jsbin with the problem or your code with the element ?

**Comment by mado-longasa** [comment] 2017-03-17 05:28
Here's my sample code with _resizeHeader

 ```
<div>
<paper-datatable-api id="table" data="{{data}}" frozen-header>
<paper-datatable-api-column header="Student" property="name">
<template>
<span>{{value}}</span>
</template>
</paper-datatable-api-column>

<template is="dom-repeat" items="{{dataColumn}}" as="header">
<paper-datatable-api-column header="[[header.name]]" property="[[header.property]]" other properties='[[_otherValues(header.dateProperty)]]'>
<template>
<div class="horizontal layout">

<table-checkbox checked$= "{{value}}" date$= "[[_computedDateProperty(otherValues, header.dateProperty)]]" content-id="[[otherValues.id]]" column = "[[header.property]]" for-edit = "true" on-edit-value="_updateCheck" class="self-center" on-error= "_error"> </table-checkbox>
 
<table-input-date date$= "[[_computedDateProperty(otherValues, header.dateProperty)]]" content-id="[[otherValues.id]]" column = "[[header.dateProperty]]" for-edit = "true"  on-edit-value="_updateDate"</table-checkbox>
 </div>
</template>
 </paper-datatable-api-column>
 </template>
</paper-datatable-api>
 </div>
```

//script

      _computedDateProperty: function(otherValues, property) {
        var value =  otherValues[property];
        return value;
      },

      _otherValues: function(dateProperty) {
        var array = [];
        array.push('id');
        array.push(dateProperty);
        return array;
      },

      _updateCheck: function(e) {
        var index = this._getIndex(this.data, e.detail.id);
        this.data[index][e.detail.column] = e.detail.value;
        this.$.table.data = JSON.parse(JSON.stringify(this.data));
        console.log(this.data);
        this.$.table._resizeHeader();
      },

      _updateDate: function(e) {
        var index = this._getIndex(this.data, e.detail.id);
        this.data[index][e.detail.column] = e.detail.value;
        this.$.table.data = JSON.parse(JSON.stringify(this.data));
        console.log(this.data);
        this.$.table._resizeHeader();
      },

      _getIndex: function(data, value) {
        for (var i = 0; i < data.length; i++) {
          if (data[i].id === value) {
            return i;
          }
        }
      },



      properties: {
        data: {
            type: Array,
            value: [{id : 1, name : 'Juan Dela Cruz', english : false, englishDate : '', math: true , mathDate : '2017-03-17',science : true,  scienceDate : '2017-03-05', socialScience : false, socialScienceDate : '',   }]
        },

        dataColumn: {
          type: Array,
          value: [{name : 'Math', property : 'math', dateProperty : 'mathDate' },
            {name : 'Science', property : 'science', dateProperty : 'scienceDate' },
            {name : 'English', property : 'english', dateProperty : 'englishDate' },
            {name : 'Social Science', property : 'socialScience', dateProperty : 'socialScienceDate' }]
        },
      }

//table-checkbox
 `<paper-checkbox checked = "{{checked}}"></paper-checkbox>`

     _update: function() {
      if (this.date !== '') {
          if (this.forEdit && this.checked !== this.tmpChecked) {
            this.tmpChecked = this.checked;
            this.fire('edit-value', {value: this.checked, id: this.contentId, column: this.column});
          } else if (!this.forEdit) {
            this.tmpChecked = this.checked;
          }
        } else {
          this.checked = false;
          this._error();
        }
      },

      _error: function() {
        this.fire('error', {errorMessage: 'Required Date'});
      },

      properties: {
        checked: {
          type: Boolean,
          value: false,
          observer: '_update'
        },

        tmpChecked: {
          type: Boolean,
          value: false
        },

        forEdit: {
          type: Boolean,
          value: false
        },

        contentId: {
          type: String
        },

        date: {
          type: String,
          value: ''
        },

        column: {
          type: String,
        }
      }


//table-input-date
`<paper-input type="date" value="{{date}}" ></paper-input>
`
   ```
 _update: function() {
        if( this.tmpDate !== undefined && this.tmpDate !== 'date' && this.date !== 'date') {
          if (this.forEdit && this.date !== this.tmpdate) {
            this.tmpDate = this.date;
            this.fire('edit-value', {value: this.date, id: this.contentId, column: this.column});
          } else if (!this.forEdit) {
            this.tmpDate = this.date;
          }
        } else {
          this.tmpDate = this.date;
        }
      },

      properties: {
        date: {
          type: String,
          value: 'date',
          observer: '_update'
        },

        tmpdate: {
          type: String,
          value: 'date',
        },

        forEdit: {
          type: Boolean,
          value: false,
        },

        contentId: {
          type: String,
        },

        column: {
          type: String,
        }
      }
```

 Screenshot of table before update   
![before update](https://cloud.githubusercontent.com/assets/17995321/24029980/2ce98bb4-0b15-11e7-8d64-ed86f6bd534a.png)

then here's the screenshot after updating Social Science Column
![after update](https://cloud.githubusercontent.com/assets/17995321/24030020/52874474-0b15-11e7-92cf-0ab0160197fd.png)

@RoXuS  Thanks :)

**Comment by RoXuS** [comment] 2017-03-17 10:29
Hi @mado-longasa,

Ok your issue is not with the header.
```
    var index = this._getIndex(this.data, e.detail.id);
    this.data[index][e.detail.column] = e.detail.value;
    this.$.table.data = JSON.parse(JSON.stringify(this.data));
    console.log(this.data);
    this.$.table._resizeHeader();
```
Here you update `data` but `paper-datatable-api` is not notified by the change. You have to use `this.set` from polymer.

For example:
```
    var index = this._getIndex(this.data, e.detail.id);
    this.data[index][e.detail.column] = e.detail.value;
    this.set('data', JSON.parse(JSON.stringify(this.data)));
    console.log(this.data);
```

In this case the header is automatically resize, can you try something like this ?

**Comment by mado-longasa** [comment] 2017-03-19 23:55
Hi @RoXuS, sorry for the late response.

I've applied but still same issue.

https://youtu.be/x4jQbESS7Pg

Thank you

**Comment by RoXuS** [comment] 2017-03-28 14:49
@mado-longasa, I can't reproduce this on my demos, can you provide me a jsbin with the bug ?

**Comment by mado-longasa** [comment] 2017-03-29 07:03
@RoXuS heres the jsbin
https://jsbin.com/cujisuvayu/1/edit?html,output

Thanks

**Comment by RoXuS** [comment] 2017-03-29 07:36
@mado-longasa here the fix : https://jsbin.com/howepunera/2/edit?html,console,output

You have to use this syntax to update your value : `this.set(`data.${index}.${e.detail.column}`, e.detail.value);`

**Comment by RoXuS** [comment] 2017-03-30 19:11
@mado-longasa for me you have a response with the jsbin so I close the issue.

If you have any other problems, don't hesitate to reopen the issue !

**Closed as completed by RoXuS** 2017-03-30 19:11 UTC

**Comment by mado-longasa** [comment] 2017-03-30 23:16
@RoXuS  Thank you very much

**Comment by mado-longasa** [comment] 2017-03-31 02:25
@RoXuS , sorry but I have new concern

encountering problem upon ticking check box 
it returns date as blank even I already set the date.

Thank you
